project:
  type: website

title: Analítica de Proyectos
subtitle: "***Integrando Python y R a la gestión de proyectos***"
author:
  - name: Juan C. Correa
    orcid: 0000-0002-0301-5641
    corresponding: TRUE
    affiliation: Critical Centrality Institute
    url: 'https://scholar.google.com/citations?user=fb0nE80AAAAJ&hl=en'
    email: j.correa.n@gmail.com
date: "Octubre 10 2024"
lang: es
bibliography: refs.bib
number-sections: true

website:
  title: ""
sidebar:
  left:
  - href: Py4DS.qmd
text: Home

format:
  html:
    theme: cosmo
css: styles.css
toc: true

editor: visual